config/routes.rb
Euparticipo::Application.routes.draw do
  root 'home#index'
  get 'index-timeline' => 'home#index_timeline', as: 'index_timeline'
  get 'convidar', to: 'invite#index', as: 'invite'

  devise_for :users,
             path: '',
             path_names: { sign_in: 'entrar', sign_up: 'cadastro', sign_out: 'sair' },
             controllers: { registrations: 'users/registrations',
                            confirmations: 'users/confirmations',
                            sessions:      'users/sessions', 
                            omniauth_callbacks: "users/omniauth_callbacks" }

  resources :preferences do
    collection do
      post :update, as: :update
    end
  end
  
  # Rotas de desenvolvimento para testar o mailing
  namespace :dev do
    resources :mailing do
      collection do
        get :confirmacao_cadastro
        get 'digest/:user_id', action: :digest
      end
    end
  end
  
  namespace :admin do
    root :to => 'dashboard#index'
    
    resources :dashboard
    resources :absent_politicians
    resources :newsletters
    resources :pending_politicians do
      member do
        get :approve
        get :deny
      end
    end
  end
  
  get 'novidades', to: 'notifications#index', as: 'notifications'
  
  # Contact
  get 'contato', to: 'about#contact', as: 'contact'
  post 'contact', to: 'about#send_contact', as: 'send_contact'

  get 'sobre', to: 'about#about', as: 'about'
  get 'privacidade', to: 'about#privacy', as: 'privacy'
  get 'termos-de-uso', to: 'about#terms', as: 'terms'
  
  get '/partials/close_window', to: 'partials#close_window', as: 'partials_close_window'

  resources :mock, path: 'mock' do
    collection do
      get :profile
    end
  end

  resources :states do
    resources :cities
  end

  resources :nudges
  resources :politician_invites, path: 'convidar-parlamentar' do
    collection do
      get 'search'
    end
    member do
      get :invite
    end
  end

  resources :allied_politicians, path: 'alie-se' do
    collection do
      get '/:position', action: 'index', as: 'position'
    end
    
    member do 
      get :ally
      get :unally
      get 'recomendar-para/:user_id', as: :recommend, action: :recommend
    end
  end
  
  resources :help, path: 'posso-ajudar', as: "posso_ajudar" do
    collection do
      get 'fale-conosco' => 'help#contact', as: 'contato'
      get 'como-funciona' => 'help#how_it_works', as: 'how_it_works'
    end
  end
  
  get '/:user_id/aliados', to: 'follows#allies', as: :allies
  get '/:user_id/acompanha', to: 'follows#following', as: :following
  get '/:user_id/acompanham', to: 'follows#followers', as: :followers

  resources :users, path: '', :except => [:edit] do
    collection do
      get 'busca' => 'users#search'
      get 'encontrar-amigos' => 'users#search', method: 'discover', as: :find_friends
    end

    member do
      get 'editar-senha'     => 'users#edit_password',   as: 'edit_password'
      post 'update-password' => 'users#update_password', as: 'update_password'

      get 'editar' => 'users#edit', as: 'edit'
      
      get 'biografia/editar' => 'users#edit_biography', as: :edit_biography
      post 'biografia/editar' => 'users#update_biography', as: :update_biography
      get 'biografia' => 'users#biography'
      
      get 'aliados' => 'users#allieds'
      get 'follow' => 'users#follow'
      get 'unfollow' => 'users#unfollow'
      #get 'aliados-a-mim' => 'users#followers', as: 'followers'
      #get 'sou-aliado-a' => 'users#followeds', as: 'followeds'
      get 'participa' => 'users#participa'
      get 'participa-timeline' => 'users#participa_timeline', as: 'participa_timeline'

      get 'dados-pessoais' => 'users#dados_pessoais', as: 'dados_pessoais'
      get 'contatos' => 'users#contatos'
      
      get 'o-que-faz' => 'users#o_que_faz', as: 'o_que_faz'

      get 'participe'                        => 'users#participe'
      get 'participe/:subpagina'             => 'users#participe_subpagina', as: 'participe_subpagina'
      get 'participe/:subpagina/timeline'    => 'users#participe_subpagina_timeline'
      
      get 'nossa-atuacao'                        => 'users#nossa_atuacao', as: 'nossa_atuacao'
      get 'nossa-atuacao/:subpagina'             => 'users#nossa_atuacao_subpagina', as: 'nossa_atuacao_subpagina'
      get 'nossa-atuacao/:subpagina/timeline'    => 'users#nossa_atuacao_subpagina_timeline'
    end
    
    resources :photos, only: [:index, :show]
    resources :user_votes, path: 'votos', as: 'votes'

    resources :posts do
      resources :comments
      get 'like-toggle' => 'posts#like_toggle', as: 'like_toggle'
      member do
        get :likes
        get :status
      end
    end
  end
  
  resources :polls do
    member do
      post 'vote'
    end
  end

  get "*a", :to => "application#routing_error"
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  layout 'clean'

  def about
  end

  def privacy
  end

  def terms
  end

  def send_contact
    ContactMailer.user_contact(params[:name], params[:email], params[:subject], params[:message]).deliver
    flash[:notice] = "Mensagem enviada com sucesso. Obrigado pelo seu contato."
    redirect_to params[:origin]
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/views/about/about.html.haml
.container.container-about
  .row
    .span4.bs-docs-sidebar
      %ul.nav.nav-list.bs-docs-sidenav.affix{'data-spy'=>'affix', 'data-offset-top'=>'120'}
        %li.active
          %a{:href => about_path}
            EuParticipo
            %i.icon-chevron-right
        %li
          %a{:href => terms_path}
            Termos de Uso
            %i.icon-chevron-right
        %li
          %a{:href => privacy_path}
            Política de Privacidade
            %i.icon-chevron-right
        %li
          %a{:href => contact_path}
            Contato
            %i.icon-chevron-right
            
    .span8.text-justify
      .pull-right
        “Nada é permanente, exceto a mudança.”
      %br
      .pull-right
        &mdash; Heráclito 
      .clearfix

      %h1 O QUE É A IDEIA?

      %p A Ideia consiste em criar uma Rede Social Virtual no Brasil com foco no engajamento político dos cidadãos. Um espaço que ofereça ao usuário da rede, através de seu perfil pessoal, diversos instrumentos funcionais para que este exerça sua cidadania política de forma criativa, acessível e concreta. Uma nova Rede Social Brasileira, não “mais uma”. Focada em política e orientada nos princípios da democracia direta.

      %p A Rede é uma iniciativa experimental, aberta, sem fins de lucro e disposta a inovar conceitos e padrões. Conectada às imprevisíveis inovações tecnológicas por que passa o mundo, busca “arrastar” a política institucional para o mundo virtual. É algo novo, dentro do novo (a Internet).

      %p Coloque sua imaginação pra funcionar... sem moderação, sem medo, esqueça a tradição, os limites. Queremos Reinventar a Política, e os Políticos. E pra isso, a Imaginação terá que tomar o Poder... e ser maior do que nós e do que está posto. O Estado é uma invenção, Poder é uma invenção, a Política é uma invenção, a Nova Política também será... Junte-se a nós, e chame mais gente. Mãos... muitas mãos, à Obra. 

      %h1 OBJETIVOS

      %p Reinventar a Política. Torna-la sábia, criativa, leve, honesta e inspiradora, fortalecendo o Poder Popular e criando condições objetivas para o surgimento de um novo Sistema Político no Brasil: A DEMOCRACIA DIRETA. 

      %p O Objetivo Maior da Rede é fazer com que o Cidadão através de um perfil disponha de vários instrumentos de participação política e exercício de cidadania. Nesta etapa inaugural o foco serão os instrumentos que possibilitem ao Cidadão a participação colaborativa junto a mandatos parlamentares.

      %h1 A ETAPA INAUGURAL – O Parlamentar Virtual

      %p A missão primeira (de democratizar os parlamentos) se justifica pela tentativa de reparar essa debilidade do sistema político nacional, onde a relação entre eleitor e eleito se resume ao instante do voto, de 4 em 4 anos. Essa debilidade assume ares curiosos quando observamos que até em mandatos executivos (de prefeitos e governadores), que são estruturas bem mais complexas, existem mais mecanismos de controle social do que em mandatos parlamentares. 

      %p Exemplos conhecidos como o orçamento participativo, conferências setoriais, conselhos de gestão já atingiram em muitos lugares o status de políticas publicas permanentes. Portanto, não seria injusto afirmar que os mandatos executivos frente aos parlamentares são mais “controlados” pela sociedade.

      %p Mais do que permitir a democratização de mandatos parlamentares, a Rede intenta pela melhoria no exercício da função, visto que a gestão compartilhada dos mandatos, onde várias “cabeças” pensam junto e onde o político reencontra aqueles que o elegeu, pode levar o exercício do mandato à excelência. Modernizar a Custo Zero, Qualificar e Popularizar a atuação parlamentar, e Possibilitar o Controle do Eleito pelos Eleitores será a tríade que pretendemos impulsionar nas casas legislativas. 

      %p Do ponto de vista dos eleitores a intenção é fortalecer o poder popular ao mesmo tempo em que se remodelam os instrumentos de que este até então dispõe. É a política sendo exercida por todos, no dia a dia. Alterando o hábito político dos eleitores. Tudo isso, através de um meio (a Internet) que se apresenta com “um caminho sem volta” na vida das pessoas, que concentra grande parte do fluxo comunicacional e tem impulsionado um novo momento político no país. 

      %p Portanto, democratizar mandatos parlamentares é a primeira intenção da Rede. E como nos propormos a fazer isso? A solução é simples. Juntaremos na Rede Cidadãos e Parlamentares de todos os níveis de poder (vereadores, deputados estaduais e federais, e senadores) cada um com perfis (página pessoal) distintos. O Cidadão ao entrar na Rede poderá, de livre escolha, se aliar com 1 parlamentar de cada nível de poder que tiver previamente se cadastrado na Rede e a partir disso poderá utilizar de forma direta, e semelhante ao Parlamentar, todos os instrumentos “burocráticos” da ação parlamentar de que o “eleito” dispõe para atuar, fazendo do Cidadão um “parlamentar virtual”. 

      %h1 CONCEITOS FUNDAMENTAIS E FUTURO

      %p Como materializar a democracia direta no mundo de hoje? Seria possível? Que impactos teria? Estas questões nos inquietam. A Rede Social EuParticipo se orienta pelos ideais da democracia direta e tenta, através de seus meios, materializá-los. Busca aperfeiçoar a democracia representativa através do engajamento político virtual, por meios ainda não institucionalizados e em um ambiente onde o fluxo de conteúdo e a moderação são auto-gestionários, onde o eixo central de atuação é o perfil do Cidadão, que disporá de diversos mecanismos para se articular e atuar politicamente, estimulando e potencializando sua intervenção política na sociedade. 

      %p Várias novas ferramentas estão previstas e serão postas no ar nos meses vindouros. Desde já afirmamos que elas seguirão nos mesmo princípios que orientam esta primeira etapa e pretendemos desenvolvê-las em plataforma COMUNITÁRIA (inclusive a Criação), assim como implantar um Governo da Rede (a República) e um Portal da Transparência dos Gastos e Receitas da mesma. Vem mais coisa por ai... 

      %h1 MUITO OBRIGADO!

      %p Muitas pessoas nos ajudaram até aqui. A todas elas queremos dirigir um agradecimento sincero, e em especial a... Felipe Rolim (por todo apoio dado na concepção técnica deste projeto, pela parceria e pelas incontáveis ajudas), a Felipe Camilo (o primeiro colaborador desta ideia), a Bruno Cavalcante e Gil Magno da Astux (pelos conselhos valiosos, esforço e brilhantismo no desenvolvimento do EuParticipo) e a toda equipe Astux (Renata Gadelha, Kim Lima e Thiago Oliveira). A Leandro Bezerra (pelo vídeo) e a Gerson Saraiva, Hemanuelle Freitas, Luana Marques, Pryscila Martins, Savio Felix e Ingrid Ramalho (pelos diversos apoios e pelo encorajamento). Obrigado!

app/views/about/contact.html.haml
.container.container-about
  .row
    .span4.bs-docs-sidebar
      %ul.nav.nav-list.bs-docs-sidenav.affix{'data-spy'=>'affix', 'data-offset-top'=>'120'}
        %li
          %a{:href => about_path}
            EuParticipo
            %i.icon-chevron-right
        %li
          %a{:href => terms_path}
            Termos de Uso
            %i.icon-chevron-right
        %li
          %a{:href => privacy_path}
            Política de Privacidade
            %i.icon-chevron-right
        %li.active
          %a{:href => contact_path}
            Contato
            %i.icon-chevron-right
    .span8.contact
      %h1 CONTATO
      = form_tag(send_contact_path, method: :post, class: 'no-bottom-margin') do |f|
        = hidden_field_tag :origin, contact_path()
        %p.control-group
          = label_tag :name, "Nome", class: 'control-label'
          = text_field_tag :name, nil, class: 'input-width', required: true
        %p.control-group
          = label_tag :email, "E-mail", class: 'control-label'
          = email_field_tag :email, nil, class: 'input-width', required: true
        %p.control-group
          = label_tag :subject, "Assunto", class: 'control-label'
          .row-fluid
            = text_field_tag :subject, nil, class: 'input-width'
        %p.control-group
          = label_tag :message, "Mensagem", class: 'control-label'
          .row-fluid
            = text_area_tag :message, nil, :rows => 15, class: 'input-width', required: true
      

        = submit_tag "Enviar", class: 'btn btn-primary pull-right'
        .clearfix

app/views/about/privacy.html.haml
.container.container-about
  .row
    .span4.bs-docs-sidebar
      %ul.nav.nav-list.bs-docs-sidenav.affix{'data-spy'=>'affix', 'data-offset-top'=>'120'}
        %li
          %a{:href => about_path}
            EuParticipo
            %i.icon-chevron-right
        %li
          %a{:href => terms_path}
            Termos de Uso
            %i.icon-chevron-right
        %li.active
          %a{:href => privacy_path}
            Política de Privacidade
            %i.icon-chevron-right
        %li
          %a{:href => contact_path}
            Contato
            %i.icon-chevron-right
            
    .span8.text-justify
    
      %p Nossos servidores guardam informações sobre os usuários da Rede EuParticipo ("Rede"). Estes termos tratam sobre estes dados e sobre a privacidade do usuário.

      %h2 Informação dadas explicitamente
      %p Ao entrar na Rede, o usuário pode informar vários dados seus, como nome, idade, cidade natal entre outros. Essas informações são armazenadas em nossos servidores até que a conta do usuário venha a ser cancelada.

      %h2 Logs de servidor web
      %p Guardamos os logs de servidor web. Usaremos tais logs para fazer relatórios de acesso às páginas e para melhoria do serviço. Nossa política de logs ainda está em definição. É provável que, após os relatórios, feitos de maneira a não identificar o usuário individualmente, nós apaguemos os logs. Atualizaremos esta política logo que esta definição for feita.

      %h2 Uso das Informações
      %p Não usaremos as informações coletadas de forma comercial. Poderemos usar informações como email do usuário para nos comunicarmos com o mesmo sobre atualizações na Rede e assuntos relevantes que julguemos serem construtivos aos usuários. Tais emails NÃO SERÃO DE MANEIRA NENHUMA disponibilizados a terceiros.

      %h2 Propriedade Intelectual Sobre o Conteúdo e Uso deste
      %p Você mantém propriedade intelectual sobre o conteúdo gerado pelo seu perfil (conta) no EuParticipo. No entanto, você concorda que temos sua licença sobre o conteúdo para, em qualquer lugar do mundo, usar, armazenar, reproduzir, modificar, criar trabalhos derivados, comunicar, publicar, mostrar publicamente, distribuir o conteúdo e elaborar melhorias na rede. 

      %h2 Segurança das Informações
      %p Esforçamo-nos para garantir a segurança dos dados dos usuários da Rede. Nossa infra-estrutura roda o Debian GNU/Linux e temos grande preferência por software livre.
      %p Nossa ação é no sentido de nos resguardar para que eventuais ataques não logrem êxito, apesar de que, assim como qualquer plataforma na Internet, não estamos completamente livres dos riscos de eventuais ataques. Por isso, não responderemos  por prejuízos que possam ser derivados da violação dessas medidas por parte de terceiros que utilizem a internet, subvertendo os sistemas de segurança para acessar as informações de Usuários.
      %p Se você tem conhecimentos em segurança da informação e quiser contribuir com a Rede, por favor, contate-nos. Toda ajuda é bem-vinda.

      %h2 Transparência
      %p Esforçar-nos-emos para manter estes termos atualizados e para informar aos usuários quando acontecerem mudanças.
      %p Nossa intenção é que a relação do usuário com a Rede seja transparente. Nossa intenção é, também, estimular o usuário a se informar sobre estes termos, por dois motivos:
      %p Porque acreditamos que, ao usar qualquer serviço (ou consumir qualquer produto), na Internet e fora dela, os usuários devem ter consciência do que é este serviço, seu histórico, o que representa e de como este serviço os trata.
      %p Porque estes termos são o registro formal que mostra o valor que o EuParticipo dá a cada usuário

      %p Remoção de conta
      %p Quando de uma remoção de conta de usuário da Rede, removeremos de nossos servidores:
      %ul
        %li Informações pessoais da conta do usuário, como foto, nome, nascimento etc.
        %li Postagens
        %li Comentários
      %p Esses dados serão efetivamente removidos de nossos servidores, o que implica que não poderemos resgatar (nem acessar) esses dados após sua remoção.

      %h2 Modificação da Política de Privacidade
      %p Esta Política de Privacidade pode modificar-se periodicamente, para correção de falhas, inclusão de melhor redação entre outros motivos. No entanto, esta Política não será modificada de forma a restringir liberdades garantidas anteriormente, por esta Política de Privacidade. Mais ainda, haverá um esforço no sentido de discutir abertamente futuras mudanças.

      %p 23 de Agosto de 2013.

app/views/about/terms.html.haml
.container.container-about
  .row
    .span4.bs-docs-sidebar
      %ul.nav.nav-list.bs-docs-sidenav.affix{'data-spy'=>'affix', 'data-offset-top'=>'120'}
        %li
          %a{:href => about_path}
            EuParticipo
            %i.icon-chevron-right
        %li.active
          %a{:href => terms_path}
            Termos de Uso
            %i.icon-chevron-right
        %li
          %a{:href => privacy_path}
            Política de Privacidade
            %i.icon-chevron-right
        %li
          %a{:href => contact_path}
            Contato
            %i.icon-chevron-right
            
    .span8.text-justify

      %p Ao se cadastrar no EuParticipo você está concordando com esses Termos de Uso ("termos").

      %h2 Nossos Termos de Uso (Garantias e Responsabilidades)
      %ul
        %li O EuParticipo é,  e sempre será, um serviço gratuito.
        %li Não nos responsabilizamos pelo conteúdo disponibilizado no EuParticipo, o mesmo é de inteira responsabilidade de seus autores.
        %li Não serão permitidas postagens que visem burlar os sistemas de pontuação e rankiamento do EuParticipo.
        %li Não serão permitidos perfis (contas) falsas, quando devidamente identificados serão excluídos.
        %li Não se fará censura. Não se restringirá a liberdade de opinião dentro do EuParticipo. 
        %li Não se poderá usar o EuParticipo para se provomer racismos e discriminações relativas à etnia, afetividade/sexualidade, classe social, gênero, geracional, religiosas ou outras previstas em lei.
        %li Não é permitida a prática de postagens com conteúdo de sexo explícito fora do contexto de uma discussão ou que não contenha conteúdo político. Assim como de postagens com conteúdo de pedofilia, exploração sexual de menores ou incentivo a esses.
        %li Não se poderá usar o EuParticipo para se distribuir dados pessoais ou confidenciais de terceiros.
        %li Não é permitida a prática de "SPAM" no EuParticipo, ou seja, qualquer tipo de postagens com intuito de desorganização ou postagens múltiplas sem conteúdo pertinente. 
        %li Não é permitido o acesso à conta de terceiros. Caso você tenha acesso a uma ou mais contas que não lhe pertençam, você deverá avisar à administração da Rede.
        %li Não é permitida a presença de perfis (contas) com o intuito de publicidade comercial.
        %li  “Bots” e outras maneiras de cadastros automáticos não são permitidos no EuParticipo.
        %li O Usuário não pode usar o serviço de nenhuma maneira ilegal.
        %li O Usuário é responsável pelo conteúdo que postar no serviço e pela atividade de sua conta (perfil) no EuParticipo.
        %li O Usuário ao detectar ou tomar conhecimento de qualquer violação a esses Termos de Uso ou a nossa Política de Privacidade deverá comunicar a administração do EuParticipo pelo email contato@euparticipo.com.br. 
        %li Estes Termos de Uso não geram nenhum contrato, mandato, franquia, vínculo trabalhista ou societário entre o EuParticipo e o Usuário. 
        %li Esforçaremos-nos para assegurar o pleno funcionamento das funcionalidades e a sua disponibilidade, porem, devido ao caráter não-empresarial de nossa gestão não garantimos que os mesmos sejam prestados de forma ininterrupta ou livre de erros. Até o limite permitido pela lei, nos excluímos de qualquer garantia sobre o serviço. Os Usuários não poderão atribuir ao EuParticipo nenhuma responsabilidade por dificuldades técnicas ou falhas nos sistemas. Eventualmente, o sistema poderá não estar disponível por motivos técnicos ou falhas da internet, ou por qualquer outro evento fortuito ou de força maior alheio ao nosso controle. Não seremos responsáveis por qualquer vírus que possa atacar o equipamento do Usuário em decorrência do acesso, utilização ou navegação no site na internet; assim como transferência de dados, arquivos, imagens, textos ou áudios.

      %h2 Modificação dos Termos de Uso
      %p Nossos Termos de Uso poderão mudar com o tempo, para correção de falhas, inclusão de melhor redação ou para se adaptar a mudanças no EuParticipo ou na lei, entre outros motivos. No entanto, estes Termos não serão modificados de forma a restringir liberdades garantidas anteriormente. Haverá um esforço no sentido de discutir abertamente futuras mudanças.

      %h2 Legislação Aplicada a Disputas
      %p Você concorda que qualquer disputa sobre esses termos ou sobre o serviço será julgada sob as leis brasileiras e, mais especificamente, quando possível, na cidade de Fortaleza, no Estado do Ceará.

      %p Em 21 de Agosto de 2013