config/routes.rb
Euparticipo::Application.routes.draw do
  root 'home#index'
  get 'index-timeline' => 'home#index_timeline', as: 'index_timeline'
  get 'convidar', to: 'invite#index', as: 'invite'

  devise_for :users,
             path: '',
             path_names: { sign_in: 'entrar', sign_up: 'cadastro', sign_out: 'sair' },
             controllers: { registrations: 'users/registrations',
                            confirmations: 'users/confirmations',
                            sessions:      'users/sessions', 
                            omniauth_callbacks: "users/omniauth_callbacks" }

  resources :preferences do
    collection do
      post :update, as: :update
    end
  end
  
  # Rotas de desenvolvimento para testar o mailing
  namespace :dev do
    resources :mailing do
      collection do
        get :confirmacao_cadastro
        get 'digest/:user_id', action: :digest
      end
    end
  end
  
  namespace :admin do
    root :to => 'dashboard#index'
    
    resources :dashboard
    resources :absent_politicians
    resources :newsletters
    resources :pending_politicians do
      member do
        get :approve
        get :deny
      end
    end
  end
  
  get 'novidades', to: 'notifications#index', as: 'notifications'
  
  # Contact
  get 'contato', to: 'about#contact', as: 'contact'
  post 'contact', to: 'about#send_contact', as: 'send_contact'

  get 'sobre', to: 'about#about', as: 'about'
  get 'privacidade', to: 'about#privacy', as: 'privacy'
  get 'termos-de-uso', to: 'about#terms', as: 'terms'
  
  get '/partials/close_window', to: 'partials#close_window', as: 'partials_close_window'

  resources :mock, path: 'mock' do
    collection do
      get :profile
    end
  end

  resources :states do
    resources :cities
  end

  resources :nudges
  resources :politician_invites, path: 'convidar-parlamentar' do
    collection do
      get 'search'
    end
    member do
      get :invite
    end
  end

  resources :allied_politicians, path: 'alie-se' do
    collection do
      get '/:position', action: 'index', as: 'position'
    end
    
    member do 
      get :ally
      get :unally
      get 'recomendar-para/:user_id', as: :recommend, action: :recommend
    end
  end
  
  resources :help, path: 'posso-ajudar', as: "posso_ajudar" do
    collection do
      get 'fale-conosco' => 'help#contact', as: 'contato'
      get 'como-funciona' => 'help#how_it_works', as: 'how_it_works'
    end
  end
  
  get '/:user_id/aliados', to: 'follows#allies', as: :allies
  get '/:user_id/acompanha', to: 'follows#following', as: :following
  get '/:user_id/acompanham', to: 'follows#followers', as: :followers

  resources :users, path: '', :except => [:edit] do
    collection do
      get 'busca' => 'users#search'
      get 'encontrar-amigos' => 'users#search', method: 'discover', as: :find_friends
    end

    member do
      get 'editar-senha'     => 'users#edit_password',   as: 'edit_password'
      post 'update-password' => 'users#update_password', as: 'update_password'

      get 'editar' => 'users#edit', as: 'edit'
      
      get 'biografia/editar' => 'users#edit_biography', as: :edit_biography
      post 'biografia/editar' => 'users#update_biography', as: :update_biography
      get 'biografia' => 'users#biography'
      
      get 'aliados' => 'users#allieds'
      get 'follow' => 'users#follow'
      get 'unfollow' => 'users#unfollow'
      #get 'aliados-a-mim' => 'users#followers', as: 'followers'
      #get 'sou-aliado-a' => 'users#followeds', as: 'followeds'
      get 'participa' => 'users#participa'
      get 'participa-timeline' => 'users#participa_timeline', as: 'participa_timeline'

      get 'dados-pessoais' => 'users#dados_pessoais', as: 'dados_pessoais'
      get 'contatos' => 'users#contatos'
      
      get 'o-que-faz' => 'users#o_que_faz', as: 'o_que_faz'

      get 'participe'                        => 'users#participe'
      get 'participe/:subpagina'             => 'users#participe_subpagina', as: 'participe_subpagina'
      get 'participe/:subpagina/timeline'    => 'users#participe_subpagina_timeline'
      
      get 'nossa-atuacao'                        => 'users#nossa_atuacao', as: 'nossa_atuacao'
      get 'nossa-atuacao/:subpagina'             => 'users#nossa_atuacao_subpagina', as: 'nossa_atuacao_subpagina'
      get 'nossa-atuacao/:subpagina/timeline'    => 'users#nossa_atuacao_subpagina_timeline'
    end
    
    resources :photos, only: [:index, :show]
    resources :user_votes, path: 'votos', as: 'votes'

    resources :posts do
      resources :comments
      get 'like-toggle' => 'posts#like_toggle', as: 'like_toggle'
      member do
        get :likes
        get :status
      end
    end
  end
  
  resources :polls do
    member do
      post 'vote'
    end
  end

  get "*a", :to => "application#routing_error"
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  scope :ordered, -> { order('created_at DESC, published_at DESC') } 
  
  validates :published, :subject, :content, presence: true
  
  before_validation :set_default_values
  
  def set_default_values
    self.published = false if self.published.blank?
  end
  
  def publish
    self.published = true
    self.published_at = DateTime.now
    self.save!
  end
end

app/controllers/admin/newsletters_controller.rb
class Admin::NewslettersController < Admin::BaseController
  respond_to :html
  
  def index
    @newsletters = Newsletter.ordered.page params[:page]
  end
  
  def new
    @newsletter = Newsletter.new
  end
  
  def create
    @newsletter = Newsletter.new resource_params
    
    if params[:commit] && params[:commit] == 'Salvar'
      flash[:notice] = 'Newsletter salva com sucesso.' if @newsletter.save
    elsif params[:commit] && params[:commit] == 'Salvar e Enviar'
      begin
        Newsletter.transaction do
          @newsletter.publish
          
          User.where(mail_newsletter: true).each do |u|
            NewsletterMailer.newsletter(u, @newsletter).deliver
          end
          
          flash[:success] = 'Newsletter publicada com sucesso. Ela será enviada nos próximos minutos.'
        end
      rescue
        @newsletter.save
        flash[:error] = 'Não foi possível enviar a newsletter.'
      end
    end
      
    respond_with @newsletter, location: admin_newsletters_path
  end
  
  def edit
    @newsletter = Newsletter.find params[:id]
  end
  
  def destroy
    @newsletter = Newsletter.find params[:id]
    if @newsletter.destroy
      flash[:success] = 'Newsletter excluída com sucesso.'
    end
    
    respond_with @newsletter, location: admin_newsletters_path
  end
  
  def resource_params
    params.require(:newsletter).permit(:subject, :content)
  end
end

app/helpers/admin/newsletters_helper.rb
module Admin::NewslettersHelper
end

app/views/admin/newsletters/_form.html.haml
= simple_form_for([:admin, @newsletter]) do |f|
  .row-fluid
    = f.input :subject, input_html: { class: 'span12' }
  .row-fluid
    = f.input :content, input_html: { class: 'span12 simple-autosize' }
  
  .form-actions
    - if !@newsletter.published?
      = f.submit "Salvar", class: 'btn btn-primary'
    
    = f.submit "Salvar e Enviar", class: 'btn btn-warning pull-right'

app/views/admin/newsletters/edit.html.haml
#content-index
  .container.container-main
    .row
      .span3
        = render 'admin/partials/left_column'
      
      .span6.main-content
        .page-header
          %h1 Administração: Editar Newsletter
          
        = render 'form'
        
        %p
          Insatisfeito? 
          = link_to 'Excluir esta Newsletter', admin_newsletter_path(@newsletter), method: :delete, data: { confirm: 'Tem certeza disto?' }
          
      .span3
        = render 'admin/partials/right_column'

app/views/admin/newsletters/index.html.haml
#content-index
  .container.container-main
    .row
      .span3
        = render 'admin/partials/left_column'
      
      .span6.main-content
        .page-header
          %h1 Administração: Newsletters
          
        .admin-toolbar
          = link_to new_admin_newsletter_path, class: 'btn btn-primary' do
            %i.icon.icon-plus.icon-white
            Criar Newsletter
        
          %hr
          
        %table.table.table-striped
          %thead
            %tr
              %th Nome
              %th Data
              %th Envio
          %tbody
            - @newsletters.each do |n|
              %tr
                %td= link_to n.subject, edit_admin_newsletter_path(n)
                %td= n.created_at.strftime("%d/%m/%y")
                %td= n.published_at.strftime("%d/%m/%y")
                
        = paginate @newsletters
          
      .span3
        = render 'admin/partials/right_column'

app/views/admin/newsletters/new.html.haml
#content-index
  .container.container-main
    .row
      .span3
        = render 'admin/partials/left_column'
      
      .span6.main-content
        .page-header
          %h1 Administração: Criar Newsletter
          
        = render 'form'
          
      .span3
        = render 'admin/partials/right_column'